### PR TITLE
[ROCKETMQ-217] Polish scheduled message example

### PR DESCRIPTION
**Pull request by lizhanhui**
https://issues.apache.org/jira/browse/ROCKETMQ-217

### CODE REVIEW

**Comment by vongosling** [comment]
LGTM, +1

**Comment by lizhanhui** [comment]
@dongeforever @zhouxinyu Any idea?

**Comment by zhouxinyu** [comment]
+1

**Comment by lizhanhui** [comment]
This PR contains contents simple enough, IMO, we can merge it directly as the original content is pretty misleading.

**Pull request closed without merging**
