### PR TITLE
Changes to the text on specifying name server list.

### PR DESCRIPTION
**Pull request by shroman**

### CODE REVIEW

**Comment by shroman** [comment]
@lizhanhui Some small changes. Just as a variant.

Also, I don't think `HTTP endpoint` should be mentioned unless there is a description on how a user can configure its own endpoint.

Another thing (not related to the docs) I thought is if a broker can be configured via a config file, why not to allow the same to producers/consumers?

**Comment by lizhanhui** [comment]
> "Also, I don't think HTTP endpoint should be mentioned unless there is a description on how a user can configure its own endpoint."

This, IMO, is the best way to configure name server addresses. Maybe we should add this endpoint to rocketmq-console project.

> "Another thing (not related to the docs) I thought is if a broker can be configured via a config file, why not to allow the same to producers/consumers?"

Good point. I think we may make the client search configuration files in classpath as many projects do, say a default.conf file containing all default values and rocketmq.conf for application user to override.

**Comment by shroman** [comment]
"This, IMO, is the best way to configure name server addresses. Maybe we should add this endpoint to rocketmq-console project."
Yes, absolutely. But my point is the user have no idea what this endpoint is (I failed to access your default one. Not accessible outside of China?) or how to set up its own :)

👍 for `rocketmq.conf`. I would also get rid of environment variable.

**Comment by lizhanhui** [comment]
@shroman We may create a JIRA ticket and thread in mailing list to follow this idea.

**Comment by shroman** [comment]
sure, I will create a JIRA issue so that this issue is not lost.
And discussing in the ml is always good ;)

Basically, that is all from me. You can merge or close this PR.

**Comment by lizhanhui** [comment]
I'll check and merge.  It looks I do not have permission to close this PR.

**Comment by lizhanhui** [comment]
This PR has been merged. @shroman you may close it.

**Pull request closed without merging**
