### PR TITLE
 [ROCKETMQ-216] - Website polish

### PR DESCRIPTION
**Pull request by zhoudiqiu**
https://issues.apache.org/jira/browse/ROCKETMQ-216

### CODE REVIEW

**Comment by vongosling** [comment]
Very pleased to see your contribution.But could you please create an issue at https://issues.apache.org/jira/browse/ROCKETMQ/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel? And also rename this pull request title, like, [ROCKETMQ-XXX] as the issue id?

**Comment by vongosling** [comment]
Looks good for me :-)

**Comment by zhouxinyu** [comment]
+1, Cool~

**Comment by dongeforever** [comment]
+1 Nice

**Pull request closed without merging**
