### PR TITLE
[ROCKETMQ-221] Website beta version finished

### PR DESCRIPTION
**Pull request by zhoudiqiu**
https://issues.apache.org/jira/browse/ROCKETMQ-221

### CODE REVIEW

**Comment by vongosling** [comment]
Could you resolve the conflict firstly

**Comment by zhoudiqiu** [comment]
Conflicts resolved, sorry about the delay

**Comment by vongosling** [comment]
+1

**Comment by lizhanhui** [comment]
+1

**Comment by lizhanhui** [comment]
This pull request has been merged and please close it at your convenient time. Thanks for your efforts and contribution.

**Comment by zhoudiqiu** [comment]
This PR will be closed, because all major changes have already been merged into the repository and there're minor bugs with CSS in this version.

**Pull request closed without merging**
